DROP DATABASE IF EXISTS search;

CREATE DATABASE search;

use search;

CREATE TABLE restaurants (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
	location VARCHAR(255) NOT NULL,
	cuisine VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE calendar (
  id INTEGER NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
);